### ISSUE TITLE
getTransactions() wrong type definition for transactionTypes

### ISSUE THREAD

**Issue by keip** [tatumio/tatum-js#1047]
it should be this:

type TransactionType = "native" | "fungible" | "nft" | "multitoken"

{ transactionTypes: TransactionType[] }

**Comment by keip** [comment]
you can try my code here: https://github.com/keip/web3

**Comment by Hathoriel** [comment]
Hello @keip 
Thank you for finding this issue I will look into it and try to resolve the issue.

**Comment by hehe100596** [comment]
Hello @keip
Thank you again for pointing out the type discrepency to us!

At the moment we are returning slightly different responses depending on whether the chain is `UTXO` or `EVM`. In the upcoming major version, we will try to unify them a bit more, but in the meantime we at least adjusted the `AddressTransaction` types in a non-breaking way - https://github.com/tatumio/tatum-js/commit/5d44b67012737b606654b575fd5e22567bdaa916
