### ISSUE TITLE
transactionType(s) used in multiple places with different values

### ISSUE THREAD

**Issue by keip** [tatumio/tatum-js#1048]
When i look up the request interface [GetAddressTransactionsQuery](https://docs.tatum.io/docs/wallet-address-operations/get-all-transactions-on-the-wallet#request-interface) there are these 2 values:

````js
transactionTypes?: TransactionType[]
transactionDirection?: 'incoming' | 'outgoing'
````

Then in the response interface [AddressTransaction](https://docs.tatum.io/docs/wallet-address-operations/get-all-transactions-on-the-wallet#response-interface) there is the `transactionType` with the type of `transactionDirection`:

````js
transactionType: 'incoming' | 'outgoing' | 'zero-transfer'
````

Then in the response data it's called `transactionSubtype` which relates to the `transactionTypes` from `GetAddressTransactionsQuery` interface.

Solution:
Chamge AddressTrasaction interface to:

````js
transactionType: TransactionType // instead of 'incoming' | 'outgoing' | 'zero-transfer'
transactionDirection: 'incoming' | 'outgoing' // instead of transactionSubtype
````

**Comment by Hathoriel** [comment]
Thank you again we will process and fix the issue.

**Comment by hehe100596** [comment]
Should be resolved for now with:
https://github.com/tatumio/tatum-js/issues/1047#issuecomment-2046793949
