### ISSUE TITLE
Filter by tokenAddress in getTransactions()

### ISSUE THREAD

**Issue by keip** [tatumio/tatum-js#1049]
It would be nice if i could filter out transactions based on tokenAddress. 
Currently it returns all transactions and to find all the transactions for a specific token can be an overload.

For example let's say i take an ETH address that has thousands of transactions and many different tokens. 
To find the transactions for a specific token i have to pull all the transactions and filter them until i find all the token transactions so in case of paging or lazy load i have to pull many unnecessary data and make more requests than needed.

**Comment by Hathoriel** [comment]
Hello @keip Thank you for submitting this issue!
We will go through it, prioritize and process your request. 
Again,
Thank you.

**Comment by oliverjantar** [comment]
Hi, this functionality was merged to master. It's in version 4.2.8. You can now pass a `tokenAddress` to filter the transactions.
