### ISSUE TITLE
✨ [Feature] Add RPC Support for BLAST ✨ 

### ISSUE THREAD

**Issue by tqmvt** [tatumio/tatum-js#1103]
Are you planning to support Blast chain?

**Comment by nader-tatum** [comment]
Thank you for your feedback! We're constantly evaluating feedback and suggestions to enhance our products. Supporting Blast chain is something we will definitely consider in our future updates.

**Comment by nader-tatum** [comment]
Thank you for your feedback! We're constantly evaluating feedback and suggestions to enhance our products. Supporting Blast chain is something we will definitely consider in our future updates.
