### ISSUE TITLE
API key for "@tatumio/api-client"

### ISSUE THREAD

**Issue by fl0ydj** [tatumio/tatum-js#1117]
**Describe the bug**
I have been using classes exposed by @tatumio/api-client (e.g. BitcoinService). Recently I started getting 401s that I have to add an API key. However, there is no option to add an api key (differently to the standard tatum SDK.

**To Reproduce**
```
import {
  BitcoinService,
} from "@tatumio/api-client";
await BitcoinService.btcGetBlockChainInfo();
```

**Additional context**
SDK version: 
```
    "@tatumio/api-client": "^2.2.81",
    "@tatumio/tatum": "^4.2.35",
```

**Comment by fl0ydj** [comment]
Any help would be appreciated!

**Comment by Hathoriel** [comment]
Hello @fl0ydj 
You can declare api client like this
```
mport { TatumBtcSDK } from '@tatumio/btc'

const btcSDK = TatumBtcSDK({ apiKey: '75ea3138-d0a1-47df-932e-acb3ee807dab' })
const { mnemonic, xpub } = await btcSDK.wallet.generateWallet()

console.log(`Created a wallet with ${mnemonic} and public key ${xpub}.`)
```

For more examples check out https://github.com/tatumio/tatum-js/tree/v2/examples.
Have a nice day.

**Comment by fl0ydj** [comment]
Hey @Hathoriel,
my question is about the "@tatumio/api-client". There you can't parse an argument for the api key.
E.g.
```
import {
  BitcoinService,
} from "@tatumio/api-client";
await BitcoinService.btcGetBlockChainInfo();
```

**Comment by fl0ydj** [comment]
Ok seeing now that the SDK reexports the api client fully.
Thanks for the pointer then.
