### ISSUE TITLE
SubscriptionType not exported

### ISSUE THREAD

**Issue by krgizdov** [tatumio/tatum-js#122]
Hello,

I am using tatum-js and I am trying to implement subscription creation.
I followed the way it is done here: https://github.com/tatumio/tatum-js/tree/master/src/ledger#create-a-subscription---detect-incoming-blockchain-transactions

I'm having problems since when I import "@tatumio/tatum" I cannot access "SubscriptionType".
From what I can see here: https://github.com/tatumio/tatum-js/blob/master/src/model/response/index.ts
it seems that SubscriptionType is not exported in the "index.ts" file.

Could you take a look at it.

Thanks in advance!

**Comment by samuelsramko** [comment]
Merged PR.
