### ISSUE TITLE
Requirements for npm install on linux

### ISSUE THREAD

**Issue by jaroslav-muller** [tatumio/tatum-js#159]
It seems that for linux (I'm having Ubuntu 20.04.3 LTS) you need to have some libraries installed before you try `npm install`.

In my case I was missing `libudev-dev`. Without it you get very cryptic errors including:
```
npm ERR! ../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
npm ERR!    40 | #include <libudev.h>
npm ERR!       |          ^~~~~~~~~~~
```

Having it mentioned in the documentation would help. ;)

**Comment by samuelsramko** [comment]
Thats actually something we didnt encounter yet. Thanks for that. Did you try to install using yarn?

**Comment by jaroslav-muller** [comment]
No, I only tried `npm`. It did a _gyp build_ and the compilation failed. When I do it now, it doesn't perform the compilation anymore, so I cannot provide details anymore. Sorry

I have npm 7.22.0 and node v16.8.0.
