### ISSUE TITLE
BCH toLegacy conversion error

### ISSUE THREAD

**Issue by glsysco** [tatumio/tatum-js#303]
When sending a BCH testnet transaction, we get the below error:

Error: qzw986csm6297rq223m30yl0md6zv3epuvdt34juk5 has no matching Script

We isolated the issue to the following lines in src/transaction/bcash.js

for (const item of to) {
        transactionBuilder.addOutput(getAddress(item.address), Number(new bignumber_js_1.default(item.value).multipliedBy(100000000).toFixed(0, bignumber_js_1.default.ROUND_FLOOR)));
    }

and linked to this:

const getAddress = (address) => {
    try {
        return wallet_1.toLegacyAddress(address);
    }
    catch (e) {
        return address;
    }
};

this outputs the following error:
'bchtest:qzw986csm6297rq223m30yl0md6zv3epuvdt34juk5'
Uncaught Error: Non-base58 character

Thx

**Comment by cgonul** [comment]
Same error for me, on the mainnet.

**Comment by Tahlil** [comment]
I think this issue still persists for V1.37.33
