### ISSUE TITLE
[Error] signatureId must be shorter than or equal to 24 characters

### ISSUE THREAD

**Issue by balmacefa** [tatumio/tatum-js#312]
```js
transaction = await deployNFT(useTestNet,
            {
                name,
                chain: "MATIC",
                symbol,
                provenance: true,
                publicMint: false,
                signatureId: 'a4873cd9-...........-7074056db3c4'
            });
```
Response with error:

`signatureId must be shorter than or equal to 24 characters`

Using the endpoint API with same payload works ok.
signatureId validation should change to  **36 characters** same as the API.

**Comment by CodeWithOz** [comment]
The same thing is happening for me, needs to be fixed please. Can anyone from the tatum team confirm when this will be fixed?

**Comment by CodeWithOz** [comment]
By the way this problem comes directly from the `/broadcast` endpoint, it's not in the js sdk. In my case I'm using the Harmony.ONE blockchain so it's `/one/broadcast`, but for the OP it would be `/polygon/broadcast`.

**Comment by belguith** [comment]
Hi facing the same validation error with  SDK func 
```
sendTransferFromCustodialWallet({chain: 'TRON',
  custodialAddress: 'FROM',
  tokenAddress: 'TOKEN_ADDRESS',
  contractType: 0,
  recipient: 'TO',
  amount: '1',
  feeLimit: 100,
  from: 'GASPUMP',
  signatureId: 'SIG_ID',
  index: INDEX
  })
```
seems to come from the same root issue 
`v3/tron/broadcast `

**Comment by samuelsramko** [comment]
Problem here is following - all `*/broadcast` endpoints accept optional singatureId parameter - which should be 24 chars long ID of the transaction, which is signed inside Tatum KMS and should be marked as completed on Tatum side. You should not directly call those endpoints with your own signatureId. I will double check the implementation inside V1 SDK, if there is proper validation present. @belguith

**Comment by samuelsramko** [comment]
this was found and closed.

**Comment by belguith** [comment]
Fixed :D :D 
may thanks @samuelsramko
