### ISSUE TITLE
incorrect return types on some functions

### ISSUE THREAD

**Issue by contra** [tatumio/tatum-js#41]
Notice these while working with the library - seems like a copy and paste issue.

- [getNFTsByAddress](https://github.com/tatumio/tatum-js/blob/7ff8439a95188ccff54a3055061fafd9fb9577b0/src/nft/index.ts#L37) has a return type of Rate which is incorrect
- [getNFTMetadataURI](https://github.com/tatumio/tatum-js/blob/7ff8439a95188ccff54a3055061fafd9fb9577b0/src/nft/index.ts#L42) has a return type of Rate which is incorrect
- [getLogRecord](https://github.com/tatumio/tatum-js/blob/7ca8f4469e76465e799a3a60ba488e2a581c6550/src/record/index.ts#L8) has a return type of Rate which is incorrect

**Comment by tatumio** [comment]
fixed in version 1.8.8
