### ISSUE TITLE
Error Installation @tatumio/eth

### ISSUE THREAD

**Issue by Droppix** [tatumio/tatum-js#457]
Hi,

I try install @tatumio/eth and I get this error

npm install @tatumio/eth
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tatumio/shared-testing@2.0.1-alpha.202.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@tatumio/eth'
npm ERR! notarget

Any idea?

**Comment by PovedaAqui** [comment]
same here

**Comment by sbunciak** [comment]
specifying the package version seems to do the thing: npm install @tatumio/celo@2.0.1-alpha.247

**Comment by PovedaAqui** [comment]
That's right. Try with the stable instead.

**Comment by PovedaAqui** [comment]
> what is the latest node version supported at the moment? I tried with node 14 and 18. Both not working for me with
> 
> npm install @tatumio/sdk

It's always recommended to use the latest stable version available.

**Comment by staminna** [comment]
Can you explain with 1 example?

**Comment by nikolaus69** [comment]
Is it old version?
