### ISSUE TITLE
Missing function for getting an NFT transaction

### ISSUE THREAD

**Issue by contra** [tatumio/tatum-js#50]
This function is missing, not sure if it was a recent addition or not - https://tatum.io/apidoc#operation/NftGetTransactErc721

The existing function to get transactions was working fine last week, then suddenly the API stopped returning a `contractAddress` when looking up a recently deployed NFT transaction. Looking at the docs it appears its not got a new endpoint which will return the contract address? Not sure what the deal is with it but either way it is missing from the JS library.

**Comment by contra** [comment]
Update: Seems like both endpoints have the same response, and neither include the contract address.

**Comment by tatumio** [comment]
Can you please share a cURL request and a response you receive?

**Comment by contra** [comment]
@tatumio After looking at both of the endpoints (the NFT specific get transaction and the main get transaction) they seem to be identical in behavior so I don't think there is any utility in adding it to the SDK. It is a little confusing to have two endpoints that do the same thing but out of scope for this ticket.
