### ISSUE TITLE
gas estimation endpoint

### ISSUE THREAD

**Issue by yocontra** [tatumio/tatum-js#54]
Doesn't seem like there is any way to call this via the SDK at the moment: https://tatum.io/apidoc#operation/EstimateFeeBlockchain

**Comment by Hathoriel** [comment]
Hi, if you want you can create pull request or we will add the method. :-)

**Comment by contra** [comment]
@Hathoriel I have a workaround calling the endpoint directly, I'm reporting the issue to you for your benefit so you can improve the SDK for other users.
