### ISSUE TITLE
Wallet Creation using Password

### ISSUE THREAD

**Issue by Amolak13** [tatumio/tatum-js#775]
### Describe the issue

How can we create a wallet on the basis of mnemonic as well as Password??

### What operating system(s) are you seeing the problem on?

macOS

### What environment do you see the problem on (Web/Node)?

Web

### What version of tatum sdk are you using?

@tatumio/btc - 2.1.6

**Comment by samuelsramko** [comment]
Hey - the password is not supported for now as an option for a wallet.
