### ISSUE TITLE
Wrong default version in NPM

### ISSUE THREAD

**Issue by Exzender** [tatumio/tatum-js#905]
By default NPM installs version 1.37.35, since it's the latest one published.
So to install actual version user have to use `npm install @tatumio/tatum@3` - but it's not obvious.
Maybe this should be mentioned in the readme?

**Comment by samuelsramko** [comment]
Hey @Exzender. This happened due to release of previous bugfix version of SDK v 1.x. We will adjust the release process, so anytime we gonna release bugfix of 1x, we will replace the latest to point to the v3. Thanks for pointing this out.
