### ISSUE TITLE
Typo in shared.dto.ts

### ISSUE THREAD

**Issue by Exzender** [tatumio/tatum-js#907]
`tokenTyoe` -> `tokenType`
https://github.com/tatumio/tatum-js/blob/411c1ba546aac5c96fabb712174719fa34dffe41/src/dto/shared.dto.ts#L53C2-L56C47

**Comment by samuelsramko** [comment]
@Hathoriel can you check this out pls?

**Comment by Smrecz** [comment]
Thank you @Exzender for pointing this out!

Fixed - https://github.com/tatumio/tatum-js/blob/d8cbd0d6ca5ef07c09489971e6d4032a7dc9bd53/src/dto/shared.dto.ts#L56
