### ISSUE TITLE
[ANNOUNCEMENT] Breaking Changes to better support Extension Ecosystem

### ISSUE THREAD

**Issue by Smrecz** [tatumio/tatum-js#929]
📢 **We're excited to announce the new Extension Ecosystem coming to the Tatum SDK!** 
With this new feature, we aim to provide a modular approach to the SDK, allowing for greater flexibility and customization.

## What is the Extension Ecosystem?
This new ecosystem allows developers to add additional features and tools as extensions to the Tatum SDK. This means that some functionalities will be moved from the core SDK to extensions for better modularity and to keep dependencies to the bare minimum.

## Breaking Changes 🚨
As a part of this transition, we'll be introducing some breaking changes. For example, all wallet providers will now be moved to extensions. The way you connect to wallet providers will also change:
Before:
```js
 tatumSdk.walletProvider.metaMask.connect()
``` 
After with MetaMask extension: 
```js
tatumSdk.walletProvider.use(MetaMask).connect()
```

## How to Prepare?
We recommend you review your implementation of the Tatum SDK and ensure you adjust your code to the upcoming changes. More details and documentation will be provided as we move closer to the release.

## Feedback
Your feedback is crucial. Let us know your thoughts, concerns, and any questions you might have below.

# Post Release Update - Breaking changes list
v4.0.0 is out with this PR [#935](https://github.com/tatumio/tatum-js/pull/935)

Check the [changelog](https://github.com/tatumio/tatum-js/blob/master/CHANGELOG.md#changed) for list of breaking changes

1. 
`tatumSdk.walletProvider.metaMask` 
was replaced with 
`tatumSdk.walletProvider.use(MetaMask)`

2. 
`tatumSdk.walletProvider.metaMask.connect()` 
was replaced with 
`tatumSdk.walletProvider.use(MetaMask).getWallet()`

3. 
`tatumSdk.walletProvider.metaMask.customPayload()` 
was replaced with 
`tatumSdk.walletProvider.use(MetaMask).signAndBroadcast()`

**Comment by Hathoriel** [comment]
@Smrecz Like it!

**Comment by samuelsramko** [comment]
1st steps - https://github.com/tatumio/tatum-js/pull/933

**Comment by Smrecz** [comment]
v4.0.0 is out with this PR [#935](https://github.com/tatumio/tatum-js/pull/935)

Check the [changelog](https://github.com/tatumio/tatum-js/blob/master/CHANGELOG.md#changed) for list of breaking changes
